"""Preserve installed npm license/NOTICE texts in the served frontend assets.

Run after npm ci and whenever dependencies change. Uninstalled optional packages
are excluded. Missing standalone texts are reported for manual follow-up rather
than inferred from a SPDX label.
"""
from pathlib import Path
import json


def main():
    root = Path(__file__).resolve().parents[1]
    frontend = root / 'frontend'
    lock = json.loads((frontend / 'package-lock.json').read_text(encoding='utf-8'))
    output = [
        'BugLens AI — installed frontend dependency notices',
        '',
        'Generated by: python scripts/update_frontend_licenses.py',
        'Scope: installed packages listed in frontend/package-lock.json, including build tools.',
        'Upstream license texts are preserved below; packages retain their own licenses.',
        'This snapshot must be regenerated after dependencies change.',
        '',
    ]
    count = 0
    missing = []
    for relative in sorted(lock.get('packages', {})):
        if not relative:
            continue
        directory = frontend / relative
        metadata_file = directory / 'package.json'
        if not metadata_file.is_file():
            continue
        metadata = json.loads(metadata_file.read_text(encoding='utf-8'))
        identity = f"{metadata.get('name', relative)}@{metadata.get('version', 'unknown')}"
        license_label = metadata.get('license', metadata.get('licenses', 'not specified'))
        if not isinstance(license_label, str):
            license_label = json.dumps(license_label, ensure_ascii=False)
        output.extend(['=' * 78, identity, f'Declared license: {license_label}', ''])
        texts = []
        candidates = list(directory.iterdir())
        for child in ('licenses', 'LICENSES', 'lib-vendor'):
            folder = directory / child
            if folder.is_dir():
                candidates.extend(p for p in folder.rglob('*') if p.is_file())
        for candidate in sorted(set(candidates)):
            name = candidate.name.upper()
            if candidate.is_file() and (name.startswith(('LICENSE', 'LICENCE', 'COPYING', 'NOTICE', 'THIRD-PARTY-LICENSE'))
                                       or candidate.parent.name.lower() == 'licenses'):
                body = candidate.read_text(encoding='utf-8', errors='replace').strip()
                if body:
                    texts.append((candidate.relative_to(directory).as_posix(), body))
        # These platform bindings declare the same MIT license and upstream
        # repository as their accompanying parent npm packages.
        parent = {'@oxlint/binding-win32-x64-msvc': 'oxlint',
                  '@rolldown/binding-win32-x64-msvc': 'rolldown'}.get(metadata.get('name'))
        if not texts and parent:
            for name in ('LICENSE', 'THIRD-PARTY-LICENSE'):
                source = frontend / 'node_modules' / parent / name
                if source.is_file():
                    texts.append((f'Accompanying {parent} package: {name}',
                                  source.read_text(encoding='utf-8').strip()))
        if metadata.get('name') == 'victory-vendor' and metadata.get('version') == '37.3.6':
            source = root / 'licenses/Victory-37.3.6-MIT.txt'
            if source.is_file():
                texts.insert(0, ('Victory v37.3.6 upstream project license',
                                 source.read_text(encoding='utf-8').strip()))
        if not texts:
            missing.append(identity)
            output.extend(['No standalone license/NOTICE text found in this installed package.',
                           'Consult its upstream distribution before bundling it separately.', ''])
        else:
            for name, body in texts:
                output.extend([f'--- {name} ---', body, ''])
        count += 1
    for name in ('Inter-OFL-1.1.txt', 'JetBrains-Mono-OFL-1.1.txt'):
        source = root / 'licenses' / name
        output.extend(['=' * 78, name, '', source.read_text(encoding='utf-8').strip(), ''])
    target = frontend / 'public/third-party-licenses.txt'
    target.write_text('\n'.join(output) + '\n', encoding='utf-8')
    print(f'Preserved notices for {count} installed packages in {target.relative_to(root)}')
    if missing:
        print('Packages without standalone license text: ' + ', '.join(missing))


if __name__ == '__main__':
    main()
